commit for the 3-th lesson
VladZhuk17/ZhukVladislav_QA17-onl pull request #2
Opened 2022-08-08 20:38 UTC by VladZhuk17

2022-08-09 19:00 UTC, nickrograch requested changes
![image](https://user-images.githubusercontent.com/48067169/183739881-ed2f5891-70dc-4352-b630-d8922c704bcc.png)
Присмотрись на пример, чего я именно я жду увидеть в консоли

2022-08-09 19:00 UTC, nickrograch commented on src/main/java/lesson3/Task1.java
> +
удали лишние пустые строки, в конце методов и классов их не должно быть - это считается мусором

2022-08-09 19:33 UTC, VladZhuk17 commented on src/main/java/lesson3/Task1.java
> +
Никита, не совсем понял, фигурные скобки в одну строку соединять таким образом }}} ? 
Когда нажимаю ctrl+alt+L он причесывает и я оставлять пустую строку между блоками методов, не оставлять?

2022-08-09 19:35 UTC, VladZhuk17 commented on src/main/java/lesson3/Task1.java
> +
Всё, понял о чем ты.

2022-08-18 03:09 UTC, nickrograch approved these changes

2022-08-18 03:09 UTC, merged